In [5]:
import pyforest
import numpy as np
import pandas as pd
import scipy.stats as ss

In [8]:
80/120

0.6666666666666666

In [12]:
120/300

0.4

In [18]:
(45+.75)-(.95)

44.8

In [25]:
p=.23
n=10
k=np.arange(0,10)
binomial = ss.binom.pmf(k,n,p)
binomial

array([7.32668047e-02, 2.18848897e-01, 2.94167024e-01, 2.34314859e-01,
       1.22482767e-01, 4.39029140e-02, 1.09282145e-02, 1.86529821e-03,
       2.08937624e-04, 1.38688755e-05])

In [27]:
p=.08
n=30
k=np.arange(0,10)
binomial1 = ss.binom.pmf(k,n,p)
binomial1

array([0.0819662 , 0.21382488, 0.26960528, 0.21881008, 0.12843201,
       0.0580736 , 0.02104116, 0.00627314, 0.00156829, 0.00033336])

In [30]:
binomial1-binomial

array([ 0.0086994 , -0.00502402, -0.02456174, -0.01550478,  0.00594924,
        0.01417069,  0.01011295,  0.00440784,  0.00135935,  0.00031949])

In [31]:
3/7

0.42857142857142855